#/appspec.yml
version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/build
  BeforeInstall:
    - location: /initialize.sh
      runas: root

  ApplicationStart:
    - location: /start.sh
      runas: root
  # ValidateService:
  #   - location: /healthCheck.sh
  #     runas: ubuntu
      # ubuntu의 $HOME 환경변수를 이용해보려고 runas ubuntu